apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup

spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: pg-dump
              image: public.ecr.aws/docker/library/postgres:17.2-bookworm@sha256:8db0b465a6524b2341a2fd5199cf54761d83b8d3336461759ef09a6c63b26751
              command:
                - bash
                - -c
                - |
                  pg_dump \
                    -f /backup/nebula.sql \
                    --if-exists \
                    --clean \
                    --column-inserts \
                    "$DATABASE_DSN"
              env:
                - name: DATABASE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: server-secrets
                      key: DATABASE_DSN
              volumeMounts:
                - name: backup
                  mountPath: /backup
              securityContext:
                allowPrivilegeEscalation: false
          volumes:
            - name: backup
              hostPath:
                path: /opt/k8s-volumes/nebula/backup
                type: DirectoryOrCreate
          restartPolicy: Never
  concurrencyPolicy: Forbid
